//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleBot.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AutoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AutoResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleBot.Shared.Resources.AutoResources", typeof(AutoResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возраст.
        /// </summary>
        public static string Age_description_VALUE {
            get {
                return ResourceManager.GetString("Age_description;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to возраст?.
        /// </summary>
        public static string Age_terms_LIST {
            get {
                return ResourceManager.GetString("Age_terms;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии.
        /// </summary>
        public static string Comments_description_VALUE {
            get {
                return ResourceManager.GetString("Comments_description;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to комментарии?.
        /// </summary>
        public static string Comments_terms_LIST {
            get {
                return ResourceManager.GetString("Comments_terms;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оценка.
        /// </summary>
        public static string Grade_description_VALUE {
            get {
                return ResourceManager.GetString("Grade_description;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to оценки?.
        /// </summary>
        public static string Grade_terms_LIST {
            get {
                return ResourceManager.GetString("Grade_terms;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id_description_VALUE {
            get {
                return ResourceManager.GetString("Id_description;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        public static string Id_terms_LIST {
            get {
                return ResourceManager.GetString("Id_terms;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to китайский?.
        /// </summary>
        public static string LangOptions_Chinese_LIST {
            get {
                return ResourceManager.GetString("LangOptions.Chinese;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Китайский.
        /// </summary>
        public static string LangOptions_Chinese_VALUE {
            get {
                return ResourceManager.GetString("LangOptions.Chinese;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to английский?.
        /// </summary>
        public static string LangOptions_English_LIST {
            get {
                return ResourceManager.GetString("LangOptions.English;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Английский.
        /// </summary>
        public static string LangOptions_English_VALUE {
            get {
                return ResourceManager.GetString("LangOptions.English;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to немецкие?.
        /// </summary>
        public static string LangOptions_German_LIST {
            get {
                return ResourceManager.GetString("LangOptions.German;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Немецкий.
        /// </summary>
        public static string LangOptions_German_VALUE {
            get {
                return ResourceManager.GetString("LangOptions.German;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to итальянский?.
        /// </summary>
        public static string LangOptions_Italian_LIST {
            get {
                return ResourceManager.GetString("LangOptions.Italian;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итальянский.
        /// </summary>
        public static string LangOptions_Italian_VALUE {
            get {
                return ResourceManager.GetString("LangOptions.Italian;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to другое.
        /// </summary>
        public static string LangOptions_Other_LIST {
            get {
                return ResourceManager.GetString("LangOptions.Other;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другой.
        /// </summary>
        public static string LangOptions_Other_VALUE {
            get {
                return ResourceManager.GetString("LangOptions.Other;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to русский?.
        /// </summary>
        public static string LangOptions_Russian_LIST {
            get {
                return ResourceManager.GetString("LangOptions.Russian;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string LangOptions_Russian_VALUE {
            get {
                return ResourceManager.GetString("LangOptions.Russian;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to испанский?.
        /// </summary>
        public static string LangOptions_Spanish_LIST {
            get {
                return ResourceManager.GetString("LangOptions.Spanish;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Испанский.
        /// </summary>
        public static string LangOptions_Spanish_VALUE {
            get {
                return ResourceManager.GetString("LangOptions.Spanish;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string Language_description_VALUE {
            get {
                return ResourceManager.GetString("Language_description;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to языки?.
        /// </summary>
        public static string Language_terms_LIST {
            get {
                return ResourceManager.GetString("Language_terms;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мессенджер.
        /// </summary>
        public static string Messenger_description_VALUE {
            get {
                return ResourceManager.GetString("Messenger_description;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мессенджер?.
        /// </summary>
        public static string Messenger_terms_LIST {
            get {
                return ResourceManager.GetString("Messenger_terms;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to facebooks?;messengers?;facebooks? messengers?.
        /// </summary>
        public static string MessengerOptions_FacebookMessenger_LIST {
            get {
                return ResourceManager.GetString("MessengerOptions.FacebookMessenger;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Messenger.
        /// </summary>
        public static string MessengerOptions_FacebookMessenger_VALUE {
            get {
                return ResourceManager.GetString("MessengerOptions.FacebookMessenger;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icqs?.
        /// </summary>
        public static string MessengerOptions_Icq_LIST {
            get {
                return ResourceManager.GetString("MessengerOptions.Icq;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icq.
        /// </summary>
        public static string MessengerOptions_Icq_VALUE {
            get {
                return ResourceManager.GetString("MessengerOptions.Icq;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to telegrams?.
        /// </summary>
        public static string MessengerOptions_Telegram_LIST {
            get {
                return ResourceManager.GetString("MessengerOptions.Telegram;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram.
        /// </summary>
        public static string MessengerOptions_Telegram_VALUE {
            get {
                return ResourceManager.GetString("MessengerOptions.Telegram;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to viber?.
        /// </summary>
        public static string MessengerOptions_Viber_LIST {
            get {
                return ResourceManager.GetString("MessengerOptions.Viber;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viber.
        /// </summary>
        public static string MessengerOptions_Viber_VALUE {
            get {
                return ResourceManager.GetString("MessengerOptions.Viber;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whats?;apps?;whats? apps?.
        /// </summary>
        public static string MessengerOptions_WhatsApp_LIST {
            get {
                return ResourceManager.GetString("MessengerOptions.WhatsApp;LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whats App.
        /// </summary>
        public static string MessengerOptions_WhatsApp_VALUE {
            get {
                return ResourceManager.GetString("MessengerOptions.WhatsApp;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Name_description_VALUE {
            get {
                return ResourceManager.GetString("Name_description;VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to имя.
        /// </summary>
        public static string Name_terms_LIST {
            get {
                return ResourceManager.GetString("Name_terms;LIST", resourceCulture);
            }
        }
    }
}
