//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleBot.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleBot.Shared.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Может воспроизводить анимированные GIF или короткие видеоролики.
        /// </summary>
        public static string Animation_Card_Sub {
            get {
                return ResourceManager.GetString("Animation_Card_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок Animation Card.
        /// </summary>
        public static string Animation_Card_Title {
            get {
                return ResourceManager.GetString("Animation_Card_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Служба приложений.
        /// </summary>
        public static string Application_Service {
            get {
                return ResourceManager.GetString("Application_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to может воспроизводить аудиофайл.
        /// </summary>
        public static string Audio_Card_Sub {
            get {
                return ResourceManager.GetString("Audio_Card_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст для Audio Card.
        /// </summary>
        public static string Audio_Card_Text {
            get {
                return ResourceManager.GetString("Audio_Card_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок Audio Card.
        /// </summary>
        public static string Audio_Card_Title {
            get {
                return ResourceManager.GetString("Audio_Card_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жирный текст.
        /// </summary>
        public static string Bold_Text {
            get {
                return ResourceManager.GetString("Bold_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привести текст к верхнему регистру.
        /// </summary>
        public static string Bring_Text_To_Uppercase {
            get {
                return ResourceManager.GetString("Bring_Text_To_Uppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привести текст к нижнему регистру.
        /// </summary>
        public static string Bring_The_Text_To_The_Lower_Case {
            get {
                return ResourceManager.GetString("Bring_The_Text_To_The_Lower_Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить текущий язык.
        /// </summary>
        public static string Change_The_Current_Language {
            get {
                return ResourceManager.GetString("Change_The_Current_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий язык русский.
        /// </summary>
        public static string Current_Language {
            get {
                return ResourceManager.GetString("Current_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обмен данными.
        /// </summary>
        public static string Data_Exchange {
            get {
                return ResourceManager.GetString("Data_Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выводит типы карт.
        /// </summary>
        public static string Display_Card_Types {
            get {
                return ResourceManager.GetString("Display_Card_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выводит доступные оформления текста.
        /// </summary>
        public static string Displays_Available_Text_Formatting {
            get {
                return ResourceManager.GetString("Displays_Available_Text_Formatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите текст.
        /// </summary>
        public static string Enter_Text {
            get {
                return ResourceManager.GetString("Enter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пример сбора данных от пользователя.
        /// </summary>
        public static string Example_Of_Data_Collection_From_A_User {
            get {
                return ResourceManager.GetString("Example_Of_Data_Collection_From_A_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получить уникальный идентификатор.
        /// </summary>
        public static string Get_Unique_Identifier {
            get {
                return ResourceManager.GetString("Get_Unique_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оказание помощи.
        /// </summary>
        public static string Giving_help {
            get {
                return ResourceManager.GetString("Giving_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок Hero Card.
        /// </summary>
        public static string Hero_Card_Title {
            get {
                return ResourceManager.GetString("Hero_Card_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Содержит одно большое изображение, одну или несколько кнопок и текст..
        /// </summary>
        public static string Hero_Card_Title_Sub {
            get {
                return ResourceManager.GetString("Hero_Card_Title_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст для Hero Card.
        /// </summary>
        public static string Hero_Card_Title_Text {
            get {
                return ResourceManager.GetString("Hero_Card_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курсив.
        /// </summary>
        public static string Italics {
            get {
                return ResourceManager.GetString("Italics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список доступных карт.
        /// </summary>
        public static string List_Of_Available_Cards {
            get {
                return ResourceManager.GetString("List_Of_Available_Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string Log_In {
            get {
                return ResourceManager.GetString("Log_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Больше информации.
        /// </summary>
        public static string More_Information {
            get {
                return ResourceManager.GetString("More_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть ссылку.
        /// </summary>
        public static string Open_Link {
            get {
                return ResourceManager.GetString("Open_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер заказа.
        /// </summary>
        public static string Order_Number {
            get {
                return ResourceManager.GetString("Order_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метод оплаты.
        /// </summary>
        public static string Payment_Method {
            get {
                return ResourceManager.GetString("Payment_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преформатированный текст.
        /// </summary>
        public static string Preformatted_Text {
            get {
                return ResourceManager.GetString("Preformatted_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цитата.
        /// </summary>
        public static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок Receipt Card.
        /// </summary>
        public static string Receipt_Card_Title {
            get {
                return ResourceManager.GetString("Receipt_Card_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок Sign-in Card.
        /// </summary>
        public static string Sign_In_Card_Title {
            get {
                return ResourceManager.GetString("Sign_In_Card_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Элемент отсортированного списка.
        /// </summary>
        public static string Sorted_List_Item {
            get {
                return ResourceManager.GetString("Sorted_List_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перечеркнутый текст.
        /// </summary>
        public static string Strikethrough_Text {
            get {
                return ResourceManager.GetString("Strikethrough_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Содержит одно небольшое изображение, одну или несколько кнопок и текст..
        /// </summary>
        public static string Thumbnail_Card_Sub {
            get {
                return ResourceManager.GetString("Thumbnail_Card_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст для Thumbnail Card.
        /// </summary>
        public static string Thumbnail_Card_Text {
            get {
                return ResourceManager.GetString("Thumbnail_Card_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок Thumbnail Card.
        /// </summary>
        public static string Thumbnail_Card_Title {
            get {
                return ResourceManager.GetString("Thumbnail_Card_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Элемент не сортированного списка.
        /// </summary>
        public static string Unordered_List_Item {
            get {
                return ResourceManager.GetString("Unordered_List_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Может воспроизводить видео.
        /// </summary>
        public static string Video_Card_Sub {
            get {
                return ResourceManager.GetString("Video_Card_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст для Video Card.
        /// </summary>
        public static string Video_Card_Text {
            get {
                return ResourceManager.GetString("Video_Card_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок Video Card.
        /// </summary>
        public static string Video_Card_Title {
            get {
                return ResourceManager.GetString("Video_Card_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваши данные успешно получены. Спасибо!.
        /// </summary>
        public static string Your_Data_Has_Been_Successfully_Received {
            get {
                return ResourceManager.GetString("Your_Data_Has_Been_Successfully_Received", resourceCulture);
            }
        }
    }
}
